# Generated by Django 5.2.14 on 2026-05-26 10:21

import django.utils.timezone
import superadmin_app.utils.encrypt_decrypt_data
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(blank=True, max_length=600, null=True, unique=True)),
                ('fullname', superadmin_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=600, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', superadmin_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=600, null=True)),
                ('role', models.CharField(blank=True, choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('Staff', 'Staff'), ('Accountant', 'Accountant'), ('Teachers', 'Teachers'), ('Students', 'Students')], max_length=100, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('permissions', models.ManyToManyField(blank=True, to='superadmin_app.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
