# Generated by Django 5.2.14 on 2026-05-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='role',
            field=models.CharField(blank=True, choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('Staff', 'Staff'), ('Accountant', 'Accountant'), ('Teacher', 'Teacher'), ('Student', 'Student')], max_length=100, null=True),
        ),
    ]
