# Generated by Django 5.2.14 on 2026-05-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0003_category_course_studentacademicdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFinancialDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('course_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('balance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('installment_plan', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='studentacademicdetails',
            name='student_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
