# Generated by Django 5.2.14 on 2026-05-27 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0004_studentfinancialdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('teacher_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('dob', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/')),
                ('address', models.TextField()),
                ('qualification', models.CharField(max_length=255)),
                ('experience_year', models.IntegerField(default=0)),
                ('specialization', models.CharField(max_length=255)),
                ('subject_expertise', models.CharField(max_length=255)),
                ('joining_date', models.DateField()),
                ('department', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('batch', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('class_timing', models.CharField(max_length=100)),
                ('reporting_admin', models.CharField(max_length=255)),
                ('salary_type', models.CharField(max_length=100)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_account', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=100)),
                ('payroll_applicable', models.BooleanField(default=False)),
                ('create_login_access', models.BooleanField(default=False)),
                ('role', models.CharField(default='Teacher', max_length=100)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('temporary_password', models.CharField(blank=True, max_length=255, null=True)),
                ('notify_teacher', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profiles', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
