# Generated by Django 5.2.14 on 2026-05-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0005_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='role',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='temporary_password',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='username',
        ),
    ]
