# Generated by Django 5.2.14 on 2026-05-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0005_category_studentfinancialdetails_remove_teacher_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='class_timing',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='section',
        ),
    ]
