# Generated by Django 5.2.14 on 2026-05-27 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0006_remove_teacher_role_remove_teacher_teacher_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin_app.category'),
        ),
    ]
