# Generated by Django 5.2.14 on 2026-05-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0007_profiles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentacademicdetails',
            name='admission_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
