# Generated by Django 5.2.14 on 2026-05-29 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0007_staffmanagementmodel_delete_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfinancialdetails',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
