# Generated by Django 5.2.14 on 2026-05-29 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0008_studentfinancialdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin_app.category'),
        ),
        migrations.AddField(
            model_name='studentacademicdetails',
            name='admission_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='fullname',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='role',
            field=models.CharField(blank=True, choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('Administration staff', 'Administration staff'), ('Non-administration staff', 'Non-administration staff'), ('Teacher', 'Teacher'), ('Student', 'Student')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentfinancialdetails',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
