# Generated by Django 5.2.14 on 2026-05-28 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0008_studentacademicdetails_admission_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfinancialdetails',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
