# Generated by Django 5.2.14 on 2026-05-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0009_studentfinancialdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='fullname',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
