# Generated by Django 5.2.14 on 2026-05-30 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0010_subject_classmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentacademicdetails',
            name='courses',
        ),
        migrations.AddField(
            model_name='studentacademicdetails',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin_app.classmodel'),
        ),
    ]
