# Generated by Django 5.2.14 on 2026-05-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0010_alter_profiles_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='Category',
            new_name='category',
        ),
    ]
