# Generated by Django 5.2.14 on 2026-05-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0011_remove_studentacademicdetails_courses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentpersonaldetails',
            old_name='parent_guardian_name',
            new_name='blood_group',
        ),
        migrations.RemoveField(
            model_name='studentpersonaldetails',
            name='parent_guardian_phone_number',
        ),
        migrations.AddField(
            model_name='studentacademicdetails',
            name='roll_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentpersonaldetails',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentpersonaldetails',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentpersonaldetails',
            name='father_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentpersonaldetails',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentpersonaldetails',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentpersonaldetails',
            name='mother_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
