# Generated by Django 5.2.14 on 2026-05-29 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0012_staffmanagementmodel_delete_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmanagementmodel',
            old_name='teacher_name',
            new_name='staff_name',
        ),
    ]
