# Generated by Django 5.2.14 on 2026-05-29 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0013_rename_teacher_name_staffmanagementmodel_staff_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmanagementmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staffmanagementmodel',
            name='phone_number',
        ),
    ]
