# Generated by Django 5.2.14 on 2026-06-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0014_teacherleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherleave',
            name='no_of_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
