# Generated by Django 5.2.14 on 2026-05-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0014_remove_staffmanagementmodel_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmanagementmodel',
            name='staff_role',
        ),
        migrations.AlterField(
            model_name='profiles',
            name='role',
            field=models.CharField(blank=True, choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('Administration staff', 'Administration staff'), ('Non-administration staff', 'Non-administration staff'), ('Teacher', 'Teacher'), ('Student', 'Student')], max_length=100, null=True),
        ),
    ]
