# Generated by Django 5.2.14 on 2026-05-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0015_remove_staffmanagementmodel_staff_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmanagementmodel',
            name='is_teacher',
            field=models.BooleanField(default=True),
        ),
    ]
