# Generated by Django 5.2.14 on 2026-06-03 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0016_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmanagementmodel',
            name='is_teacher',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teacherleave',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_leaves', to='superadmin_app.staffmanagementmodel'),
        ),
        migrations.CreateModel(
            name='SubstituteTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('period', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin_app.classmodel')),
                ('original_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_teacher_assignments', to='superadmin_app.staffmanagementmodel')),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_teacher_assignments', to='superadmin_app.staffmanagementmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TeachersTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin_app.category')),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin_app.classmodel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin_app.staffmanagementmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('students_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin_app.classmodel')),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin_app.staffmanagementmodel')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
