# Generated by Django 5.2.14 on 2026-06-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0018_alter_studentattendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherleave',
            name='SubstituteTeacher',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=120),
        ),
    ]
