# Generated by Django 5.2.14 on 2026-06-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0018_staffmanagementmodel_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpersonaldetails',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
