# Generated by Django 5.2.14 on 2026-05-30 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0019_remove_staffmanagementmodel_student_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin_app.classmodel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin_app.staffmanagementmodel')),
            ],
        ),
    ]
