# Generated by Django 5.2.14 on 2026-06-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0019_teacherleave_substituteteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherleave',
            name='SubstituteTeacher',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
