# Generated by Django 5.2.14 on 2026-05-30 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0020_teacherstimetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherstimetable',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin_app.category'),
        ),
    ]
