# Generated by Django 5.2.14 on 2026-06-03 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0020_profiles_address_profiles_dob_profiles_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='dob',
        ),
    ]
