# Generated by Django 5.2.14 on 2026-05-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0022_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('forgot_password', 'Forgot Password')], default='forgot_password', max_length=50),
        ),
    ]
