# Generated by Django 5.2.14 on 2026-06-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0022_loginhistory_passwordresetaudit_usersession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='status',
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='login_status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('LOGOUT', 'LOGOUT')], default='SUCCESS', max_length=20),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='raw_user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_id',
            field=models.TextField(),
        ),
    ]
