# Generated by Django 5.2.14 on 2026-06-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0023_alter_otpverification_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
