# Generated by Django 5.2.14 on 2026-06-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0023_alter_usersession_options_remove_loginhistory_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='login_status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('LOGOUT', 'LOGOUT')], db_index=True, default='SUCCESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_id',
            field=models.TextField(unique=True),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', 'created_at'], name='superadmin__user_id_375e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['login_status'], name='superadmin__login_s_0e4f59_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='superadmin__user_id_6e30e3_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='superadmin__expires_2bb8ca_idx'),
        ),
    ]
