# Generated by Django 5.2.14 on 2026-06-01 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0024_otpverification_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentpersonaldetails',
            old_name='parent_guardian_name',
            new_name='blood_group',
        ),
        migrations.RemoveField(
            model_name='studentpersonaldetails',
            name='parent_guardian_phone_number',
        ),
        migrations.AddField(
            model_name='studentacademicdetails',
            name='previous_institute',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentacademicdetails',
            name='roll_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentpersonaldetails',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentpersonaldetails',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentpersonaldetails',
            name='father_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentpersonaldetails',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentpersonaldetails',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentpersonaldetails',
            name='mother_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin_app.staffmanagementmodel')),
            ],
        ),
    ]
