# Generated by Django 5.2.14 on 2026-06-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0024_alter_loginhistory_login_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='token_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
