# Generated by Django 5.2.14 on 2026-06-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0025_profiles_token_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='token_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_id',
            field=models.CharField(db_index=True, help_text='Stores JWT JTI (token identifier), not the full JWT token.', max_length=128, unique=True),
        ),
    ]
