# Generated by Django 5.2.14 on 2026-06-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0025_rename_parent_guardian_name_studentpersonaldetails_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student', 'date')},
        ),
    ]
