# Generated by Django 5.2.14 on 2026-06-01 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0026_alter_studentattendance_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Casual Leave', 'Casual Leave'), ('Sick Leave', 'Sick Leave'), ('Emergency Leave', 'Emergency Leave'), ('Half Day Leave', 'Half Day Leave'), ('Permission', 'Permission'), ('Other', 'Other')], max_length=50)),
                ('date', models.DateField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('no_of_days', models.PositiveIntegerField(blank=True, null=True)),
                ('half_day_type', models.CharField(blank=True, choices=[('First Half', 'First Half'), ('Second Half', 'Second Half')], max_length=20, null=True)),
                ('reason', models.TextField()),
                ('reachable_contact_number', models.CharField(max_length=15)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='leave_documents/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_leaves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
