# Generated by Django 5.2.14 on 2026-06-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0024_otpverification_secret'),
        ('superadmin_app', '0027_alter_loginhistory_user'),
    ]

    operations = [
    ]
