# Generated by Django 5.2.14 on 2026-06-01 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0027_teacherleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='students_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin_app.classmodel'),
        ),
    ]
