# Generated by Django 5.2.14 on 2026-06-02 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0028_studentattendance_students_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstituteTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('period', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin_app.classmodel')),
                ('original_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_teacher_assignments', to='superadmin_app.staffmanagementmodel')),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_teacher_assignments', to='superadmin_app.staffmanagementmodel')),
            ],
        ),
    ]
