# Generated by Django 5.2.14 on 2026-06-02 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0029_substituteteacherassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherleave',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_leaves', to='superadmin_app.staffmanagementmodel'),
        ),
    ]
