# Generated by Django 5.2.14 on 2026-06-04 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0031_alter_studentattendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Half Day', 'Half Day')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('checked_in_time', models.TimeField(blank=True, null=True)),
                ('checked_out_time', models.TimeField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin_app.staffmanagementmodel')),
            ],
            options={
                'unique_together': {('teacher', 'date')},
            },
        ),
    ]
