# Generated by Django 5.2.14 on 2026-06-04 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0032_teachersattendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeachersAttendance',
            new_name='TeacherstaffAttendance',
        ),
    ]
