# Generated by Django 5.2.14 on 2026-06-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0033_rename_teachersattendance_teacherstaffattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherleave',
            name='SubstituteTeacher',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
