# Generated by Django 5.2.14 on 2026-06-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0034_teacherleave_substituteteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherstaffattendance',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
