# Generated by Django 5.2.14 on 2026-06-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_app', '0035_teacherstaffattendance_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherstaffattendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Half day', 'Half day')], max_length=20),
        ),
    ]
